// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX04fvCI3BNwynz593YSzcdSVi2rNHINs',
    appId: '1:265396333806:web:f61822d652db25ea8ad7ff',
    messagingSenderId: '265396333806',
    projectId: 'tutorial-firestore-169e5',
    authDomain: 'tutorial-firestore-169e5.firebaseapp.com',
    storageBucket: 'tutorial-firestore-169e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUdJr-GjbE4BJauQ87v4UIJ6AsWR0tGDA',
    appId: '1:265396333806:android:63260232c614b6ae8ad7ff',
    messagingSenderId: '265396333806',
    projectId: 'tutorial-firestore-169e5',
    storageBucket: 'tutorial-firestore-169e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs_29MamqUcM0QTM_Pzkr5X62_DWzo-bs',
    appId: '1:265396333806:ios:d594fa8514f8055e8ad7ff',
    messagingSenderId: '265396333806',
    projectId: 'tutorial-firestore-169e5',
    storageBucket: 'tutorial-firestore-169e5.appspot.com',
    iosBundleId: 'com.example.tutorialFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs_29MamqUcM0QTM_Pzkr5X62_DWzo-bs',
    appId: '1:265396333806:ios:fda72d1c5ddb11828ad7ff',
    messagingSenderId: '265396333806',
    projectId: 'tutorial-firestore-169e5',
    storageBucket: 'tutorial-firestore-169e5.appspot.com',
    iosBundleId: 'com.example.tutorialFirestore.RunnerTests',
  );
}
